spring:
  application:
    name: ApiBackend
  datasource:
    url: jdbc:mysql://localhost:3306/douyin
    username: root
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        boot:
          allow_jdbc_metadata_access: false
logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.api.apibackend: DEBUG
  file:
    name: logs/application.log  # 日志文件路径
    path: logs                  # 日志目录
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"