spring:
  application:
    name: ApiBackend
  datasource:
    url: jdbc:mysql://localhost:3306/douyin
    username: root
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        boot:
          allow_jdbc_metadata_access: false